#!/usr/bin/env node
// Generates a fresh EVM and Solana keypair for use as a *test* buyer wallet
// against this server's testnet routes (Base Sepolia / Solana Devnet).
//
// These are throwaway keys with no funds. Never use generated keys, or this
// script's approach, for mainnet/production wallets.
//
// Usage:
//   node scripts/generate-keys.mjs            # print keys to the terminal
//   node scripts/generate-keys.mjs --write     # also append to .env.local

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { createKeyPairFromPrivateKeyBytes } from "@solana/keys";
import { base58 } from "@scure/base";

// --- EVM (Base Sepolia) ---
const evmPrivateKey = generatePrivateKey();
const evmAccount = privateKeyToAccount(evmPrivateKey);

// --- Solana (Devnet) ---
const seed = globalThis.crypto.getRandomValues(new Uint8Array(32));
const { publicKey } = await createKeyPairFromPrivateKeyBytes(seed, true);
const pubkeyBytes = new Uint8Array(await globalThis.crypto.subtle.exportKey("raw", publicKey));
const svmSecretKeyBytes = new Uint8Array(64);
svmSecretKeyBytes.set(seed, 0);
svmSecretKeyBytes.set(pubkeyBytes, 32);
const svmPrivateKey = base58.encode(svmSecretKeyBytes);
const svmAddress = base58.encode(pubkeyBytes);

console.log(`
Generated a fresh TEST buyer wallet (testnet only — do not fund with real assets):

EVM (Base Sepolia)
  Address:     ${evmAccount.address}
  Private key: ${evmPrivateKey}
  Faucet:      https://portal.cdp.coinbase.com/products/faucet
               (also need Base Sepolia USDC: https://faucet.circle.com)

Solana (Devnet)
  Address:     ${svmAddress}
  Private key: ${svmPrivateKey}
  Faucet:      https://faucet.solana.com (select Devnet)
               (also need Devnet USDC: https://faucet.circle.com)
`);

if (process.argv.includes("--write")) {
  const envPath = ".env.local";
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  const additions = `
# --- test buyer wallet (generated by scripts/generate-keys.mjs) ---
EVM_PRIVATE_KEY=${evmPrivateKey}
SVM_PRIVATE_KEY=${svmPrivateKey}
`;
  writeFileSync(envPath, existing + additions);
  console.log(`Appended EVM_PRIVATE_KEY / SVM_PRIVATE_KEY to ${envPath}`);
}
